name: PS Vita CMAKE

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    name: ${{ matrix.target }} USE_VITAGL=${{ matrix.use_vitagl }} NO_GUI=${{ matrix.no_gui }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [MVS, NCDZ] # CPS1, CPS2 require desktop port first
        use_vitagl: [ON, OFF] # Build both vita2d and VitaGL versions
        no_gui: [ON] # TODO: OFF when GUI is ported
        exclude:
          - target: CPS1
          - target: CPS2
      fail-fast: false

    container: vitasdk/vitasdk:latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apk add build-base git bash cmake

    - name: Install vita2d (for non-VitaGL builds)
      if: matrix.use_vitagl == 'OFF'
      run: |
        git clone https://github.com/xerpi/vita2dlib
        cd vita2dlib/libvita2d
        make install

    - name: Install VitaGL (for VitaGL builds)
      if: matrix.use_vitagl == 'ON'
      run: |
        # Install vitashark
        git clone https://github.com/Rinnegatamante/vitashark
        cd vitashark
        make install
        cd ..
        
        # Install VitaGL
        git clone https://github.com/Rinnegatamante/vitaGL
        cd vitaGL
        make install

    - name: Compile project
      run: |
        mkdir build
        cd build
        cmake -DPLATFORM="PSVITA" \
          -DCMAKE_TOOLCHAIN_FILE=${VITASDK}/share/vita.toolchain.cmake \
          -DTARGET="${{ matrix.target }}" \
          -DUSE_VITAGL=${{ matrix.use_vitagl }} \
          -DNO_GUI=${{ matrix.no_gui }} \
          ..
        make -j $(getconf _NPROCESSORS_ONLN)
        cmake --install .

    - name: Get short SHA
      id: slug
      run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: NJEMU-${{ steps.slug.outputs.sha8 }}-PSVITA-${{ matrix.target }}-vitagl_${{ matrix.use_vitagl }}-no_gui_${{ matrix.no_gui }}
        path: build/install/
